[data]
tile_ids = """
[D][D][D][D][D][D][D][D][D][D][D][D][D][D][D][D][D][D][D][D][D][D][D][D][D]
[D][d][d][d][l][D][D][D][D][D][D][D][D][D][D][D][D][D][D][D][D][D][D][D][D]
[D][d][d][l][l][D][D][D][D][D][D][D][D][D][D][D][D][D][D][D][D][D][D][D][D]
[D][d][d][l][l][D][D][D][D][D][D][D][D][D][D][D][D][D][D][D][D][D][D][D][D]
[D][d][l][d][d][d][d][d][d][D][D][D][D][D][D][D][D][D][D][D][D][D][D][D][D]
[D][d][d][d][d][D][D][D][d][d][d][D][D][D][D][D][D][D][D][D][D][D][D][D][D]
[D][D][D][D][D][D][D][D][D][D][d][D][D][D][D][D][D][d][d][d][d][d][D][D][D]
[D][D][D][D][D][D][D][D][D][D][d][D][D][D][D][D][D][d][d][d][d][d][D][D][D]
[D][D][D][D][D][D][D][D][D][D][d][D][D][D][D][D][D][d][d][D][d][d][D][D][D]
[D][D][D][D][D][D][D][D][d][d][d][d][D][D][D][D][D][d][d][d][d][d][D][D][D]
[D][D][D][D][D][D][D][D][d][d][d][d][D][D][D][D][D][d][d][d][d][d][D][D][D]
[D][D][D][D][D][D][D][D][d][d][d][d][d][D][D][D][D][d][d][D][d][d][d][D][D]
[D][D][D][D][D][D][D][D][d][d][d][d][d][D][D][D][D][d][d][D][d][d][d][D][D]
[D][D][D][D][D][D][D][D][d][d][d][d][d][D][D][D][D][d][d][D][d][d][d][d][D]
[D][D][D][D][D][D][D][D][d][d][d][d][d][D][D][D][D][D][D][D][d][d][d][d][D]
[D][D][D][D][D][D][D][D][D][D][l][l][D][D][D][D][D][D][D][D][d][d][D][D][D]
[D][D][D][D][D][D][D][D][D][D][l][l][D][D][D][D][D][D][D][D][d][d][D][D][D]
[D][D][D][D][D][D][D][D][D][D][D][l][l][l][l][D][D][D][D][D][d][d][D][D][D]
[D][D][D][D][D][D][D][D][D][D][D][D][l][l][l][l][D][D][D][D][D][D][D][D][D]
[D][D][D][D][D][D][D][D][D][D][D][D][l][l][l][D][D][D][D][D][D][D][D][D][D]
[D][D][D][D][D][D][D][D][D][D][D][D][D][l][D][D][D][D][D][D][D][D][D][D][D]
[D][D][D][D][D][D][D][D][D][D][D][D][D][D][D][D][D][D][D][D][D][D][D][D][D]
"""
