[imp]

[imp.base]
id = "imp"
bg_color = nan
fg_color = 8
name = "Imp"

[imp.animation]
idle = [
    [
        ":Ö:", ":Ö:", ":Ö:", ":Ö:", ":Ö:", ":Ö:", ":Ö:", ":Ö:",
        ":Ö:", ":Ö:", ";Ô;", ";Ô;", ";Ô;", ";Ô;", ":Ö:", ":Ö:",
    ],
]
walk = [[";Ö:", ";Ö:", ";Ö;", ";Ö;", ":Ö;", ":Ö;"]]
