[dirt_wall]
bgcolor = "black"
fgcolor = "light_black"
name = "dirt wall"
floor_state = "solid"
block_state = "solid"
pixels = [["###"]]

[dirt_floor]
bgcolor = "black"
fgcolor = "light_black"
name = "dirt floor"
floor_state = "solid"
block_state = "gas"
pixels = [
    ["   "],
    ["   "],
    ["'  "],
    [" . "],
    ["  '"],
    [",  "],
    [", ."],
    [",: "],
    [" :."],
    ["' :"],
]

[lava_floor]
bgcolor = "red"
fgcolor = "black"
name = "lava floor"
floor_state = "solid"
block_state = "gas"
pixels = [
    [".  ", " '."],
    ["~  ", " ~ ", "  ~", "   "],
    ["<  ", " ^ ", "  >", " v "],
    ["'  ", "-  ", ".  ", " , ", "  .", "  -", "  '", " ' "],
]

[multiline_test]
name = """\
    Hello \
    World\
"""
pp = [
    [1, 2, 3],
    [4, 5, 6],
]
