[bedrock]
id = "[#]"
bg_color = 0
fg_color = 8
name = "bedrock"
floor_state = "solid"
block_state = "solid"
tile_strings = [["###"]]

[dirt_wall]
id = "[:]"
bg_color = 0
fg_color = 8
name = "dirt wall"
floor_state = "solid"
block_state = "solid"
tile_strings = [[", '"]]

[dirt_floor]
id = "[_]"
bg_color = 8
fg_color = 7
name = "dirt floor"
floor_state = "solid"
block_state = "gas"
tile_strings = [
    [
        "   ", "   ", "   ", "   ", "   ", "   ", "   ", "   ",
        "   ", "   ", "   ", "   ", "   ", "   ", "   ", "   ",
        "   ", "   ", "   ", "   ", "   ", "   ", "   ", "   ",
        "   ", "   ", "   ", "   ", "   ", "   ", "   ", "   ",
        ".  ", ".  ", "'  ", "'  ", " - ", "  ,", "  .", "  .",
    ],
    ["   "],
    ["   "],
    ["'  "],
    [" . "],
    ["  '"],
    [",  "],
    [", ."],
    [",: "],
    [" :."],
    ["' :"],
]

[lava_floor]
id = "[v]"
bg_color = 1
fg_color = 0
name = "lava floor"
floor_state = "solid"
block_state = "gas"
tile_strings = [
    #[":-O", "   ", "   ", "   ", "   ", "   ", "   ", "   "],
    #[":-)", ":-)", ":-)", ":-)", ":-D", ":-D", ":-D", ":-D"],
    #[".  ", " '."],
    #["~  ", " ~ ", "  ~", "   "],
    #["<  ", " ^ ", "  >", " v "],
    #["'  ", "-  ", ".  ", " , ", "  .", "  -", "  '", " ' "],
    ["~  ", "~  ", " ~ ", " ~ ", "  ~", "  ~", "~  ", "~  "],
    ["~  ", "~  ", " ~ ", " ~ ", "  ~", "  ~", " ~ ", " ~ "],
    [
        "~  ", "~  ", "~  ", "~  ", "~  ", "~  ", "~  ", "~  ",
        " ~ ", " ~ ", " ~ ", " ~ ", " ~ ", " ~ ", " ~ ", " ~ ",
        "  ~", "  ~", "  ~", "  ~", "  ~", "  ~", "  ~", "  ~",
        " ~ ", " ~ ", " ~ ", " ~ ", " ~ ", " ~ ", " ~ ", " ~ ",
    ],
    ["000", "001", "002", "003", "004", "005", "006", "007", "008", "009", "010", "011", "012"],
    ["AAA", "BBB", "CCC"],
]
